// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAzDODzL_SpS2_kBk8MYVqHBd6rbt-pE7Y',
    appId: '1:20433148762:web:7b8019f06a41dc83e8f163',
    messagingSenderId: '20433148762',
    projectId: 'promissorynotemanager',
    authDomain: 'promissorynotemanager.firebaseapp.com',
    storageBucket: 'promissorynotemanager.appspot.com',
    measurementId: 'G-P1YM06P1X2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBiao8ofOPBYLyPdIxqOd6QO2ddlmXT2dA',
    appId: '1:20433148762:android:d8130379e990556ae8f163',
    messagingSenderId: '20433148762',
    projectId: 'promissorynotemanager',
    storageBucket: 'promissorynotemanager.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF7IbWHpsUfx96ynv-n7U9gqHqW2hDYaE',
    appId: '1:20433148762:ios:6930ba3ec47ef6e8e8f163',
    messagingSenderId: '20433148762',
    projectId: 'promissorynotemanager',
    storageBucket: 'promissorynotemanager.appspot.com',
    androidClientId: '20433148762-9716bs27eceqpeusan0isi0tomhsel6i.apps.googleusercontent.com',
    iosClientId: '20433148762-8falh9n4p7m4jpfqft8kg0egm7r7ulht.apps.googleusercontent.com',
    iosBundleId: 'com.example.promissorynotemanager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF7IbWHpsUfx96ynv-n7U9gqHqW2hDYaE',
    appId: '1:20433148762:ios:6930ba3ec47ef6e8e8f163',
    messagingSenderId: '20433148762',
    projectId: 'promissorynotemanager',
    storageBucket: 'promissorynotemanager.appspot.com',
    androidClientId: '20433148762-9716bs27eceqpeusan0isi0tomhsel6i.apps.googleusercontent.com',
    iosClientId: '20433148762-8falh9n4p7m4jpfqft8kg0egm7r7ulht.apps.googleusercontent.com',
    iosBundleId: 'com.example.promissorynotemanager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAzDODzL_SpS2_kBk8MYVqHBd6rbt-pE7Y',
    appId: '1:20433148762:web:be39f260f431180ee8f163',
    messagingSenderId: '20433148762',
    projectId: 'promissorynotemanager',
    authDomain: 'promissorynotemanager.firebaseapp.com',
    storageBucket: 'promissorynotemanager.appspot.com',
    measurementId: 'G-TGCJNGH3NZ',
  );
}
